### ISSUE TITLE
Legacy Twitch API v5 Shutdown

### ISSUE THREAD

**Issue by Nickwasused** [twireapp/Twire#236]
### Problem
The V5 Twitch Api is going to shut down on **February 28, 2022**. Migration to the new Helix Api should be completed before  **February 7, 2022**.

### Timeline

- February 7, 2022 – 1-hour shutdown starting at 11:00am PDT
- February 9, 2022 – 2-hour shutdown starting at 11:00am PDT
- February 14, 2022 – 4-hour shutdown starting at 11:00am PDT
- February 16, 2022 – 6-hour shutdown starting at 11:00am PDT
- February 21, 2022 – 24-hour shutdown starting at 11:00am PDT
- February 28, 2022 – v5 permanent shutdown

### Source:
https://blog.twitch.tv/en/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/
https://discuss.dev.twitch.tv/t/legacy-twitch-api-v5-shutdown-details-and-timeline/32649

# To-Do
- [x] MyStreams (#240)
- [x] TopStreams (#240)
- [x] TopGames (#240)
- [x] JSONService (#240)
- [x] Featured Streams (#240)
- [x] Android Deep Links (#240)
- [x] Stream Count (#240)
- [x] misc/Followhandler (#240)
- [x] Channels Activity (#240)
- [ ] Search
- [ ] Vod Chat Log (Possible Problem https://twitch.uservoice.com/forums/310213-developers/suggestions/44063160-vod-chat-for-helix)
- [x] Get Stream Viewers (#240)
- [x] Streams Service (Removed in #240)
- [x] Service/getStreamerInfoFromUserId (#240)
- [x] User Login (#240)

**Comment by Perflyst** [comment]
Just leaving this here:
```
We are reaching out as we have identified that your application(s) below
have made requests to v5 API endpoints in January and may be affected by
the upcoming shutdown if further action is not taken.


Twire
GET /kraken/streams, GET /kraken/users/:id, PUT
/kraken/users/:user_id/follows/channels/:channel_id, GET
/kraken/videos/:vod_id/comments, GET /kraken/search/games, GET
/kraken/search/streams, DELETE
/kraken/users/:user_id/follows/channels/:channel_id, GET
/kraken/streams/:id, GET /kraken/search/channels, GET
/kraken/users/:user_id/emotes, GET /kraken/channels/:id, GET
/kraken/streams/followed, GET /kraken/users, GET /kraken/streams/featured,
GET /kraken/user, GET /kraken/channels/:user_id/videos, GET
/kraken/users/:user_id/follows/channels, GET /kraken/games/top, GET
/kraken/videos/:vod_id
```
